apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-stg 

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-stg


  template:
    metadata:
      labels:
        app: nginx-stg
    spec:
      containers:
        - name: stg-nginx
          image: nginx 
          ports:
          - containerPort: 80
