apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-app

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: demo-app


  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: stg
          image: sunilchouha/nginx:v1.0.0
          ports:
          - containerPort: 80
