apiVersion: apps/v1
kind: Deployment

metadata: 
  name: nginx-deploy
  namespace: nginx-1

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests: 
            cpu: "100m"
          limits: 
            cpu: "200m"