apiVersion: v1
kind: PersistentVolume

metadata:
  name: notes-pv
  namespace: notes 

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce
  
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data 
