apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-v1
  namespace: test

spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: test 
      version: v1
  template:
    metadata:
      labels:
        app: test
        version: v1

    spec:
      containers:
        - name: app
          image: hashicorp/http-echo
          args:
            - "-text=Hello from VERSION 1"
          ports:
          - containerPort: 5678