apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-v2
  namespace: test

spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: test 
      version: v2
  template:
    metadata:
      labels:
        app: test
        version: v2

    spec:
      containers:
        - name: app
          image: hashicorp/http-echo
          args:
            - "-text=Hello from VERSION 2"
          ports:
          - containerPort: 5678