apiVersion: v1
kind: PersistentVolume

metadata: 
  name: demo-pv
  namespace: nginx

spec: 
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/demo 
