kind: ReplicaSet
apiVersion: apps/v1

metadata: 
  name: nginx-replicaset
  namespace: nginx-ns
  labels: 
    app: nginx-rep

spec: 
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod

  template:
    metadata:
      labels:
        app: nginx-pod
      
    spec: 
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80