apiVersion: batch/v1
kind: Job
metadata:
  name: presync-sleep
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sleep
          image: busybox
          command: ["sh", "-c", "echo 'Waiting 20 seconds...'; sleep 20"]
  backoffLimit: 0