apiVersion: v1
kind: Pod 

metadata: 
  name: config-secret-demo
  namespace: demo

spec:
  containers:
    - name: demo
      image: nginx
      env:  
        - name: APP_MESSAGE 
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_MESSAGE
        
        - name: USERNAME
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: USERNAME

        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD