apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-dev 

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-dev 


  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
        - name: dev-nginx
          image: nginx 
          ports:
          - containerPort: 80
