apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deploy 

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-po 


  template:
    metadata:
      labels:
        app: nginx-po
    spec:
      containers:
        - name: demo-nginx
          image: nginx 
          ports:
          - containerPort: 80
