apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-prod 

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-prod 


  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
        - name: prod-nginx
          image: nginx 
          ports:
          - containerPort: 80
